from flask import Flask,render_template,make_response,redirect,url_for
from datetime import datetime
app = Flask(__name__)

@app.route('/home/')
def home():
    now = datetime.now()
    return render_template('home.html',now=now)

@app.route('/about')
def about():
    headers = {'Content-Type': 'application/json'}
    return make_response('This response is generated by make response',200,headers)

@app.route('/redirect')
def redirect_route():
    return redirect(url_for('home'))

@app.route('/search')
def search():
    return redirect('https://www.google.com')

@app.route('/base',methods=['GET','POST'])

def base():
    return render_template('base.html')


if __name__ == '__main__':
    app.run(debug=True)